//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Historical
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RESBazaEntities : DbContext
    {
        public RESBazaEntities()
            : base("name=RESBazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tabela1> Tabela1 { get; set; }
        public virtual DbSet<Tabela2> Tabela2 { get; set; }
        public virtual DbSet<Tabela3> Tabela3 { get; set; }
        public virtual DbSet<Tabela4> Tabela4 { get; set; }
        public virtual DbSet<Tabela5> Tabela5 { get; set; }
    }
}
