//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Historical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabela1
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Timestamp { get; set; }
        public string ValueID { get; set; }
        public string Potrosnja { get; set; }
        public string VrijemeUpisa { get; set; }
    }
}
